### ISSUE TITLE
curl --get results in error

### ISSUE THREAD

**Issue by zhengliw** [TheGuywithTheHat/noip-ipv6-duc#3]
The curl line has also to be fixed. Curl throws an error saying similar to "illegal url format or missing url".

This can be fixed by removing `--get`.

Again, I just fixed this randomly. I'm not familiar with bash XD

**Comment by dairiki-ren** [comment]
Update: i think that removing --get rather broke the script than repairing it. So i did some research, maybe set -x GET will solve the problem.

**Comment by TheGuywithTheHat** [comment]
Passing data with `-d "hostname=$hostname" -d "myipv6=$addr"` will make curl automatically switch to POST instead of the default GET. No-IP's dynamic DNS service wants it to use GET, so the `--get` flag is passed in to force curl to GET instead of POST. `-X GET` might accomplish the same thing, but `--get` appears to work fine for me.

**Comment by TheGuywithTheHat** [comment]
`illegal url format or missing url` is likely a different issue; were you running my script exactly? Can you provide the full error, if there is any more detail at all?

**Comment by dairiki-ren** [comment]
I stopped using the script becuz I noticed that it wasn't possible to use ddns with my isp. But if you just run the script normally, it throws this error.
